In [97]:
import numpy as np
from numpy import linalg as LA

In [63]:
matrix = np.array([[2., 3., 5., 1., 4.], [500., 700., 1800., 300., 1200.], [2., 1., 2., 3., 2.]])

In [64]:
matrix

array([[2.0e+00, 3.0e+00, 5.0e+00, 1.0e+00, 4.0e+00],
       [5.0e+02, 7.0e+02, 1.8e+03, 3.0e+02, 1.2e+03],
       [2.0e+00, 1.0e+00, 2.0e+00, 3.0e+00, 2.0e+00]])

In [65]:
matrix.shape

(3, 5)

In [68]:
D = matrix.shape[0]
for row in range(D):
    mean, stddev = np.mean(matrix[row,:]), np.std(matrix[row,:])   
    print(f'row = {row}, mean = {mean}, stddev = {stddev}')
    matrix[row,:] = (matrix[row,:] - mean)/stddev 

row = 0, mean = 0.0, stddev = 1.4142135623730951
row = 1, mean = 0.0, stddev = 540.3702434442519
row = 2, mean = 0.0, stddev = 0.6324555320336759


In [69]:
matrix

array([[-0.70710678,  0.        ,  1.41421356, -1.41421356,  0.70710678],
       [-0.74023321, -0.37011661,  1.66552472, -1.11034982,  0.55517491],
       [ 0.        , -1.58113883,  0.        ,  1.58113883,  0.        ]])

In [70]:
def cov_naive(X):
    """Compute the covariance for a dataset of size (D,N) 
    where D is the dimension and N is the number of data points"""
    D, N = X.shape
    covariance = np.zeros((D, D))

    for i in range(D):
        for j in range(i, D):                      
            x = X[i, :]
            y = X[j, :]
            sum_xy = np.dot(x, y) / N
            if i == j:
                covariance[i, j] = sum_xy
            else:                        
                covariance[i, j] = covariance[j, i] = sum_xy
    return covariance

In [71]:
cov_naive(matrix)

array([[ 1.        ,  0.96833426, -0.4472136 ],
       [ 0.96833426,  1.        , -0.23408229],
       [-0.4472136 , -0.23408229,  1.        ]])

In [75]:
def cov_naive_2(X):
    """Compute the covariance for a dataset of size (D,N) 
    where D is the dimension and N is the number of data points"""
    D, N = X.shape
    covariance = np.zeros((D, D))
    
    for i in range(N):                     
        x = X[:, i]
        covariance += np.outer(x, x)
    return covariance/N

In [76]:
cov_naive_2(matrix)

array([[ 1.        ,  0.96833426, -0.4472136 ],
       [ 0.96833426,  1.        , -0.23408229],
       [-0.4472136 , -0.23408229,  1.        ]])

In [74]:
np.cov(matrix, bias=True)  

array([[ 1.        ,  0.96833426, -0.4472136 ],
       [ 0.96833426,  1.        , -0.23408229],
       [-0.4472136 , -0.23408229,  1.        ]])

In [92]:
from numpy import linalg as LA

test = np.array([2, 3, 5, 1, 4])
idx = test.argsort()[::-1]  

In [93]:
# np.take_along_axis(test, idx, axis=0)

In [96]:
idx

array([2, 4, 1, 0, 3])

In [98]:
def eig(S):
    """Compute the eigenvalues and corresponding eigenvectors 
        for the covariance matrix S.
    Args:
        S: ndarray, covariance matrix
    
    Returns:
        (eigvals, eigvecs): ndarray, the eigenvalues and eigenvectors

    Note:
        the eigenvals and eigenvecs should be sorted in descending
        order of the eigen values
    """
    eig_values, eig_vectors = LA.eig(S)
    idx = eig_values.argsort()[::-1]   
    eig_values = eig_values[idx]
    eig_vectors = eig_vectors[:,idx]
    return (eig_values, eig_vectors)

In [107]:
matrix = np.array([[1, 2, 3], [2, 1, 8]])
cov_matrix = np.cov(matrix, bias=True)

In [108]:
eig_values, eig_vectors = eig(cov_matrix)

In [109]:
eig_vectors

array([[-0.2098553 , -0.97773245],
       [-0.97773245,  0.2098553 ]])